[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "CONFIG_STRIPE_KEY,CONFIG_STRIPE_WEBHOOK_KEY,CONFIG_VOSFACTURES_KEY,CONFIG_VOSFACTURES_DOMAIN,CONFIG_VOSFACTURES_TEST,CONFIG_ACTIVATE_KEY,CONFIG_MAILGUN_ID,CONFIG_MAILGUN_KEY"
